"""AD-15 migration guard, on a scratch `*_pytest` database it creates and drops itself.

The guard reaches Alembic through `config.attributes["connection"]` (AD-21 step 1). The `%`
tests pin the URL steps: a caller-set `sqlalchemy.url` goes through configparser, so `%` must
be escaped as `%%`.
"""

from collections.abc import Iterator
from pathlib import Path
from uuid import uuid4

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import Connection, create_engine, make_url, text

from app.db import make_engine
from tests.helpers import PERCENT_PASSWORD, public_tables
from tests.settings import TestSettings

TEST_DATABASE_URL = TestSettings().test_database_url
ALEMBIC_INI = Path(__file__).resolve().parents[1] / "alembic.ini"


@pytest.fixture()
def scratch_connection() -> Iterator[Connection]:
    server_url = make_url(TEST_DATABASE_URL)
    name = f"todo_migrations_{uuid4().hex[:12]}_pytest"
    admin = create_engine(server_url, isolation_level="AUTOCOMMIT")
    try:
        with admin.connect() as connection:
            connection.execute(text(f'CREATE DATABASE "{name}"'))
        try:
            engine = make_engine(server_url.set(database=name).render_as_string(False))
            try:
                with engine.connect() as connection:
                    yield connection
            finally:
                engine.dispose()
        finally:
            with admin.connect() as connection:
                connection.execute(text(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)'))
    finally:
        admin.dispose()


def alembic_config(connection: Connection) -> Config:
    config = Config(str(ALEMBIC_INI))
    config.attributes["connection"] = connection
    return config


def test_migrations_have_one_head_upgrade_cleanly_and_match_models(
    scratch_connection: Connection,
) -> None:
    config = alembic_config(scratch_connection)

    assert len(ScriptDirectory.from_config(config).get_heads()) == 1

    command.upgrade(config, "head")
    scratch_connection.commit()
    command.check(config)  # raises AutogenerateDiffsDetected on model/migration drift

    assert scratch_connection.execute(text("SELECT 1")).scalar_one() == 1
    tables = scratch_connection.execute(
        text("SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename")
    ).scalars()
    assert list(tables) == ["alembic_version", "tasks"]


def test_caller_url_with_escaped_percent_reaches_the_engine(percent_password_url: str) -> None:
    config = Config(str(ALEMBIC_INI))
    config.set_main_option("sqlalchemy.url", percent_password_url.replace("%", "%%"))

    assert make_url(config.get_main_option("sqlalchemy.url") or "").password == PERCENT_PASSWORD

    command.upgrade(config, "head")  # logs in only if the engine got the password intact

    assert public_tables(percent_password_url) == ["alembic_version", "tasks"]


def test_caller_url_with_unescaped_percent_is_refused(percent_password_url: str) -> None:
    config = Config(str(ALEMBIC_INI))

    with pytest.raises(ValueError, match="interpolation"):
        config.set_main_option("sqlalchemy.url", percent_password_url)
